########################################################################
start_epoch: 0
max_epoch: 4 #1

############################continue train setting#########################
which_epoch:  4
continue_train:  True #
########################################################################

optimizer_G:
  lr:   [0.00001]         #
  lr_policy:  origin

optimizer_D:
  lr:  [0.00001]
  lr_policy: origin  #origin #lambda2