########################################################################
start_epoch: 0 
max_epoch: 9 

############################continue train setting#########################
which_epoch:  8
continue_train:  True 
########################################################################

optimizer_G:
  lr:  [0.00001]   
  lr_policy: origin 
