########################################################################
start_epoch: 0 
max_epoch: 9  

############################continue train setting#########################
which_epoch:  8 #start #21 #10 #
continue_train:  True #False #True #True #
########################################################################

optimizer_G:
  lr:   [0.00001]         #
  lr_policy:  origin

optimizer_C:
  lr:  [0.00001,0.00001]
  lr_policy: origin 
