########################################################################
start_epoch: 0
max_epoch: 49 #1

############################continue train setting#########################
which_epoch:  40
continue_train:  True 
########################################################################

optimizer_G:
  lr:   [0.00001]         
  lr_policy:  origin

optimizer_D:
  lr:  [0.00001]
  lr_policy: origin  
